#!/usr/bin/env pwsh

[CmdletBinding()]
param(
    [switch]$DryRunOnly,
    [switch]$CreateFeatureBranch,
    [string]$TitlePrefix = "Deep Test PBI"
)

$ErrorActionPreference = 'Stop'

function Add-Result {
    param(
        [System.Collections.Generic.List[object]]$Results,
        [string]$Name,
        [string]$Status,
        [string]$Details = ""
    )

    $Results.Add([PSCustomObject]@{
        name = $Name
        status = $Status
        details = $Details
    })
}

$results = [System.Collections.Generic.List[object]]::new()

Write-Host "=== spec-kit Deep ADO Workflow Test ===" -ForegroundColor Cyan

try {
    npm test | Out-Null
    Add-Result -Results $results -Name 'npm test' -Status 'PASS'
} catch {
    Add-Result -Results $results -Name 'npm test' -Status 'FAIL' -Details $_.Exception.Message
}

try {
    npm pack --dry-run | Out-Null
    Add-Result -Results $results -Name 'npm pack --dry-run' -Status 'PASS'
} catch {
    Add-Result -Results $results -Name 'npm pack --dry-run' -Status 'FAIL' -Details $_.Exception.Message
}

try {
    & .\.specify\scripts\powershell\test-functionality.ps1 | Out-Null
    Add-Result -Results $results -Name 'test-functionality.ps1' -Status 'PASS'
} catch {
    Add-Result -Results $results -Name 'test-functionality.ps1' -Status 'FAIL' -Details $_.Exception.Message
}

$testTitle = "$TitlePrefix $(Get-Date -Format 'yyyyMMdd-HHmmss')"

try {
    $dryCreate = & .\.specify\scripts\powershell\create-pbi-for-specify.ps1 -Title $testTitle -DryRun -Json | Out-String | ConvertFrom-Json
    Add-Result -Results $results -Name 'create-pbi-for-specify.ps1 -DryRun' -Status 'PASS' -Details ($dryCreate.fieldsApplied -join ', ')
} catch {
    Add-Result -Results $results -Name 'create-pbi-for-specify.ps1 -DryRun' -Status 'FAIL' -Details $_.Exception.Message
}

$createdPbiId = $null

if (-not $DryRunOnly) {
    try {
        $liveCreate = & .\.specify\scripts\powershell\create-pbi-for-specify.ps1 `
            -Title $testTitle `
            -Description 'deep test validation item' `
            -AcceptanceCriteria 'created by deep-test-ado-workflow.ps1' `
            -Tags 'deep-test;spec-kit' `
            -Priority 3 `
            -State 'To Do' `
            -Json | Out-String | ConvertFrom-Json
        $createdPbiId = [int]$liveCreate.pbiId
        Add-Result -Results $results -Name 'create-pbi-for-specify.ps1 live' -Status 'PASS' -Details "AB#$createdPbiId"
    } catch {
        Add-Result -Results $results -Name 'create-pbi-for-specify.ps1 live' -Status 'FAIL' -Details $_.Exception.Message
    }

    if ($createdPbiId) {
        try {
            & .\.specify\scripts\powershell\select-pbi-for-specify.ps1 -PbiId $createdPbiId | Out-Null
            Add-Result -Results $results -Name 'select-pbi-for-specify.ps1' -Status 'PASS' -Details "AB#$createdPbiId"
        } catch {
            Add-Result -Results $results -Name 'select-pbi-for-specify.ps1' -Status 'FAIL' -Details $_.Exception.Message
        }
    }
}

try {
    $pushDryRun = & .\.specify\scripts\powershell\push-pbi-refinements.ps1 -DryRun -Json 2>&1 | Out-String
    Add-Result -Results $results -Name 'push-pbi-refinements.ps1 -DryRun' -Status 'PASS' -Details ($pushDryRun.Trim())
} catch {
    $message = $_.Exception.Message
    if ($message -match 'Could not determine the active feature spec path') {
        Add-Result -Results $results -Name 'push-pbi-refinements.ps1 -DryRun' -Status 'SKIP' -Details 'Requires active feature branch/spec context generated by /speckit.specify.'
    }
    else {
        Add-Result -Results $results -Name 'push-pbi-refinements.ps1 -DryRun' -Status 'FAIL' -Details $message
    }
}

if ($CreateFeatureBranch -and $createdPbiId) {
    try {
        & .\.specify\scripts\powershell\create-feature-from-pbi.ps1 -PbiId $createdPbiId -WorkType feature -Description 'deep-test-branch' | Out-Null
        $branchName = (git rev-parse --abbrev-ref HEAD).Trim()
        Add-Result -Results $results -Name 'create-feature-from-pbi.ps1' -Status 'PASS' -Details $branchName
        git checkout master | Out-Null
    } catch {
        Add-Result -Results $results -Name 'create-feature-from-pbi.ps1' -Status 'FAIL' -Details $_.Exception.Message
    }
}

Write-Host ""
Write-Host "Results:" -ForegroundColor Cyan
foreach ($result in $results) {
    $color = if ($result.status -eq 'PASS') { 'Green' } elseif ($result.status -eq 'SKIP') { 'Yellow' } else { 'Red' }
    Write-Host ("[{0}] {1}" -f $result.status, $result.name) -ForegroundColor $color
    if ($result.details) {
        Write-Host ("  {0}" -f $result.details) -ForegroundColor Gray
    }
}

$failed = @($results | Where-Object { $_.status -eq 'FAIL' }).Count
exit $(if ($failed -gt 0) { 1 } else { 0 })